from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[('core','0008_executive_management_suite')]
    operations=[
        migrations.AddField(
            model_name='employeeprofile',
            name='birth_date',
            field=models.DateField(blank=True,null=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),
                ('action',models.CharField(max_length=40)),
                ('path',models.CharField(max_length=255)),
                ('method',models.CharField(max_length=10)),
                ('object_type',models.CharField(blank=True,max_length=80)),
                ('object_id',models.CharField(blank=True,max_length=80)),
                ('summary',models.CharField(blank=True,max_length=250)),
                ('metadata',models.JSONField(blank=True,default=dict)),
                ('ip_address',models.GenericIPAddressField(blank=True,null=True)),
                ('created_at',models.DateTimeField(auto_now_add=True)),
                ('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='audit_logs',to='auth.user')),
            ],
            options={'ordering':['-created_at']},
        ),
        migrations.AddIndex(model_name='auditlog',index=models.Index(fields=['-created_at'],name='core_auditl_created_idx')),
        migrations.AddIndex(model_name='auditlog',index=models.Index(fields=['actor','-created_at'],name='core_auditl_actor_idx')),
        migrations.CreateModel(
            name='ManagementEvent',
            fields=[
                ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),
                ('title',models.CharField(max_length=180)),
                ('event_type',models.CharField(choices=[('meeting','جلسه'),('deadline','سررسید'),('training','آموزش'),('reminder','یادآوری'),('other','سایر')],default='other',max_length=20)),
                ('date',models.DateField()),
                ('time',models.TimeField(blank=True,null=True)),
                ('description',models.TextField(blank=True)),
                ('created_at',models.DateTimeField(auto_now_add=True)),
                ('branch',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='management_events',to='core.branch')),
                ('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='created_management_events',to='auth.user')),
            ],
            options={'ordering':['date','time','title']},
        ),

        migrations.CreateModel(
            name='CEOScoreSnapshot',
            fields=[
                ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),
                ('date',models.DateField()),
                ('score',models.PositiveSmallIntegerField()),
                ('people',models.PositiveSmallIntegerField()),
                ('operations',models.PositiveSmallIntegerField()),
                ('revenue',models.PositiveSmallIntegerField()),
                ('discipline',models.PositiveSmallIntegerField()),
                ('details',models.JSONField(blank=True,default=dict)),
                ('created_at',models.DateTimeField(auto_now_add=True)),
                ('branch',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='ceo_score_snapshots',to='core.branch')),
            ],
            options={'ordering':['-date']},
        ),
        migrations.AddConstraint(
            model_name='ceoscoresnapshot',
            constraint=models.UniqueConstraint(fields=('date','branch'),name='uniq_ceo_score_date_branch'),
        ),
    ]
