# Generated by Django 5.2.17 on 2026-08-31 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_employeeprofile_personnel_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplate',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'مدیر سیستم'), ('manager', 'مدیر شعبه'), ('employee', 'کارمند'), ('referrer', 'معرف مشتری')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر سیستم'), ('manager', 'مدیر شعبه'), ('employee', 'کارمند'), ('referrer', 'معرف مشتری')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='ReferralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='referrals/people/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('crm_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('sync_status', models.CharField(choices=[('local', 'محلی'), ('pending', 'در صف ارسال'), ('synced', 'همگام\u200cشده'), ('error', 'خطای همگام\u200cسازی')], db_index=True, default='local', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referral_profiles', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.referralprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReferralLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('alternate_phone', models.CharField(blank=True, max_length=30)),
                ('interested_service', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شد'), ('appointment', 'نوبت ثبت شد'), ('visited', 'مراجعه کرد'), ('won', 'فروش موفق'), ('lost', 'ناموفق')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(choices=[('panel', 'ثبت در پنل'), ('link', 'لینک اختصاصی'), ('qr', 'QR اختصاصی'), ('import', 'ورودی فایل')], default='panel', max_length=20)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('crm_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('sync_status', models.CharField(choices=[('local', 'محلی'), ('pending', 'در صف ارسال'), ('synced', 'همگام\u200cشده'), ('error', 'خطای همگام\u200cسازی')], db_index=True, default='local', max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_referral_leads', to='core.employeeprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referral_leads', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.referralprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('direct_commission', models.DecimalField(decimal_places=0, default=0, help_text='سهم معرف مستقیم به تومان', max_digits=18)),
                ('level_two_commission', models.DecimalField(decimal_places=0, default=0, help_text='سهم معرف بالادستی به تومان', max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('paid', 'پورسانت پرداخت شد'), ('cancelled', 'لغو شده')], db_index=True, default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('crm_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('sync_status', models.CharField(choices=[('local', 'محلی'), ('pending', 'در صف ارسال'), ('synced', 'همگام\u200cشده'), ('error', 'خطای همگام\u200cسازی')], db_index=True, default='local', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='core.referrallead')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_referral_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referrallead',
            index=models.Index(fields=['referrer', 'status', '-created_at'], name='reflead_ref_status_idx'),
        ),
    ]
