# Generated by Django 5.2.17 on 2026-09-14 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_delete_test1_staff_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiServerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(default='http://192.168.40.33:81/gl-api', max_length=500)),
                ('api_key_cipher', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('appointment_confirmation_enabled', models.BooleanField(default=False)),
                ('appointment_message_template', models.TextField(default='گرین لایف\n{name} عزیز، نوبت شما در شعبه {branch} برای تاریخ {date} ساعت {time} ثبت شد.\n02134247')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_api_server_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تنظیمات API Server',
                'verbose_name_plural': 'تنظیمات API Server',
            },
        ),
        migrations.CreateModel(
            name='SmsMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20)),
                ('body', models.TextField()),
                ('purpose', models.CharField(choices=[('test', 'آزمایشی'), ('manual', 'دستی'), ('appointment', 'تأیید نوبت')], db_index=True, default='manual', max_length=20)),
                ('status', models.CharField(choices=[('accepted', 'پذیرفته\u200cشده'), ('failed', 'ناموفق')], db_index=True, max_length=20)),
                ('provider_ids', models.JSONField(blank=True, default=list)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='core.visitappointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='sms_status_created_idx')],
            },
        ),
    ]
