from .lead_management_views import lead_management_dashboard as _dashboard


def lead_management_dashboard(request):
    response = _dashboard(request)
    if getattr(response, 'status_code', 500) != 200 or not hasattr(response, 'content'):
        return response
    try:
        html = response.content.decode(response.charset or 'utf-8')
        admin = bool(request.user.is_superuser or (getattr(request.user, 'profile', None) and request.user.profile.role == 'admin'))
        extra = '''<style id="lead-row-dark-fix">
body.gl-premium-dark .lead-page table tr,body.gl-premium-dark .lead-page table tr:hover,body.gl-premium-dark .lead-page table tr:focus,body.gl-premium-dark .lead-page table tr:focus-within,body.gl-premium-dark .lead-page table tr:active,body.gl-premium-dark .lead-page table td,body.gl-premium-dark .lead-page table td:hover,body.gl-premium-dark .lead-page table td:focus{background-color:#10151e!important;background-image:none!important;color:#f8fafc!important}
body.gl-premium-dark .lead-page table thead tr,body.gl-premium-dark .lead-page table thead tr:hover,body.gl-premium-dark .lead-page table th{background:linear-gradient(90deg,#173c32 0%,#252243 52%,#172d3d 100%)!important;color:#e5edf6!important}
body.gl-premium-dark .lead-page table a:focus,body.gl-premium-dark .lead-page table button:focus{outline:2px solid #7c5cff!important;outline-offset:2px}.lead-admin-actions{display:inline-flex;align-items:center;gap:5px;margin:0;white-space:nowrap;flex-wrap:nowrap}.lead-admin-actions a{display:inline-flex;align-items:center;justify-content:center;min-height:28px;padding:5px 8px;border-radius:8px;text-decoration:none!important;font-size:9px;font-weight:900;white-space:nowrap}.lead-admin-edit{background:#173b34!important;color:#77e4c1!important;border:1px solid #2f6f61}.lead-admin-delete{background:#3a1b24!important;color:#ff9aaa!important;border:1px solid #713244}
/* Compact all-leads table on tablet/desktop. */
.lead-page .lead-table{table-layout:fixed!important;width:100%!important;min-width:0!important}.lead-page .lead-all-table{min-width:1280px!important}.lead-page .lead-table th,.lead-page .lead-table td{padding:8px 6px!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}.lead-page .lead-table .lead-col-name{width:14%!important;max-width:150px!important}.lead-page .lead-table .lead-col-desc{width:28%!important;max-width:320px!important}.lead-page .lead-table .lead-col-name,.lead-page .lead-table .lead-col-desc{cursor:pointer}.lead-page .scroll-x{overflow-x:auto!important;scrollbar-width:thin}@media(max-width:900px){.lead-page .lead-table{font-size:9px!important}.lead-page .lead-table th,.lead-page .lead-table td{padding:7px 4px!important}.lead-page .lead-table .lead-col-name{width:13%!important}.lead-page .lead-table .lead-col-desc{width:25%!important}}
/* All-leads balance: spend the reclaimed gaps on a readable, exact source. */
.lead-page .lead-all-table{font-size:9.5px!important}
.lead-page .lead-all-table th,.lead-page .lead-all-table td{padding-left:4px!important;padding-right:4px!important}
.lead-page .lead-all-table .lead-col-time{width:9%!important}.lead-page .lead-created-at{white-space:nowrap!important}.lead-page .lead-created-date,.lead-page .lead-created-time{display:block!important}.lead-page .lead-created-time{font-size:11px!important;font-weight:800!important;margin-top:3px!important}
.lead-page .lead-all-table .lead-col-name{width:11%!important;max-width:none!important}
.lead-page .lead-all-table .lead-col-mobile{width:10%!important}
.lead-page .lead-all-table .lead-col-source{width:11%!important;max-width:none!important;font-size:10.5px!important;text-overflow:ellipsis!important}
.lead-page .lead-all-table .lead-col-desc{width:23%!important;max-width:none!important;white-space:normal!important;line-height:1.65!important;text-overflow:clip!important}
.lead-page .lead-all-table .lead-col-operator{width:8%!important}
.lead-page .lead-all-table .lead-col-group{width:9%!important;max-width:none!important;white-space:normal!important;line-height:1.5!important;text-overflow:clip!important}
.lead-page .lead-all-table .lead-col-status{width:10%!important}.lead-page .lead-all-table .lead-col-result{width:12%!important;min-width:135px!important;white-space:normal!important;overflow:visible!important;text-overflow:clip!important}
@media(max-width:900px){.lead-page .lead-all-table{font-size:8.8px!important}.lead-page .lead-all-table .lead-col-source{width:16%!important;font-size:9.5px!important}.lead-page .lead-all-table .lead-col-desc{width:25%!important}.lead-page .lead-all-table .lead-col-group{width:10%!important}}
/* Urgent queue final fit: wider identity, slightly larger status, compact follow-up, guaranteed action rail. */
.lead-page .lead-urgent-table{table-layout:fixed!important;width:100%!important}.lead-page .lead-urgent-table th,.lead-page .lead-urgent-table td{vertical-align:middle!important}.lead-page .lead-urgent-table .lead-urgent-name{width:31%!important;min-width:270px!important;white-space:normal!important;overflow:visible!important}.lead-page .lead-urgent-table .lead-urgent-name>span:first-child{font-size:16px!important;font-weight:900!important;line-height:1.5!important}.lead-page .lead-urgent-table .lead-urgent-name small,.lead-page .lead-urgent-table .lead-urgent-name>span:not(:first-child){font-size:10.5px!important;line-height:1.55!important}.lead-page .lead-urgent-table .lead-urgent-status{width:10%!important;max-width:125px!important;padding-left:3px!important;padding-right:3px!important}.lead-page .lead-urgent-table .lead-urgent-status .badge{font-size:10px!important;padding:6px 10px!important;white-space:nowrap!important}.lead-page .lead-urgent-table .lead-urgent-followup{width:8%!important;max-width:105px!important}.lead-page .lead-urgent-table .lead-urgent-actions-cell,.lead-page .lead-urgent-table .lead-urgent-actions-head{width:22%!important;min-width:275px!important;overflow:visible!important;text-overflow:clip!important;white-space:nowrap!important}.lead-page .lead-urgent-actions{display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:5px!important;flex-wrap:nowrap!important;white-space:nowrap!important}.lead-page .lead-urgent-actions>a,.lead-page .lead-urgent-actions .lead-admin-actions a{display:inline-flex!important;align-items:center!important;justify-content:center!important;box-sizing:border-box!important;height:28px!important;min-height:28px!important;padding:5px 8px!important;margin:0!important;border-radius:8px!important;white-space:nowrap!important;line-height:1.2!important;font-size:9px!important;font-weight:900!important}.lead-page .lead-urgent-table tbody tr{height:auto!important}.lead-page .lead-urgent-table tbody td{padding-top:7px!important;padding-bottom:7px!important}
@media(max-width:900px){.lead-page .lead-urgent-table{min-width:1180px!important}.lead-page .lead-urgent-table .lead-urgent-name{width:31%!important;min-width:260px!important}.lead-page .lead-urgent-table .lead-urgent-name>span:first-child{font-size:15px!important}.lead-page .lead-urgent-table .lead-urgent-status{width:10%!important}.lead-page .lead-urgent-table .lead-urgent-status .badge{font-size:10px!important;padding:6px 9px!important}.lead-page .lead-urgent-table .lead-urgent-followup{width:8%!important}.lead-page .lead-urgent-table .lead-urgent-actions-cell,.lead-page .lead-urgent-table .lead-urgent-actions-head{width:22%!important;min-width:275px!important}.lead-page .lead-urgent-actions,.lead-page .lead-admin-actions{gap:5px!important}.lead-page .lead-urgent-actions>a,.lead-page .lead-urgent-actions .lead-admin-actions a{height:28px!important;min-height:28px!important;padding:5px 8px!important;font-size:9px!important}}
.lead-page .lead-result{font-size:9.5px!important;padding:5px 8px!important;white-space:nowrap!important}
.lead-page .lead-result-follow_up{background:#6b3d09!important;color:#ffd28a!important;border-color:#9b5a12!important}
.lead-page .lead-result-appointment,.lead-page .lead-result-won{background:#0d593c!important;color:#a8f1cf!important;border-color:#17865d!important}
.lead-page .lead-result-no_answer{background:#364150!important;color:#e5edf6!important;border-color:#536174!important}
.lead-page .lead-result-sale_lost{background:#6b2027!important;color:#ffc1c7!important;border-color:#a53a45!important}
.lead-page .lead-result-not_interested{background:#303640!important;color:#d7dde5!important;border-color:#525b68!important}
</style>'''
        compact = '''<script id="lead-table-compact">document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.lead-page .lead-table').forEach(function(table){var heads=Array.from(table.querySelectorAll('thead th')),map={};heads.forEach(function(th,i){var t=(th.textContent||'').trim();if(t==='خدمت'){th.textContent='توضیحات';t='توضیحات'}if(t==='زمان')map.time=i;if(t==='نام')map.name=i;if(t==='موبایل')map.mobile=i;if(t==='منبع')map.source=i;if(t==='توضیحات')map.desc=i;if(t==='اپراتور')map.operator=i;if(t==='گروه')map.group=i;if(t==='وضعیت')map.status=i;if(t==='نتیجه تماس')map.result=i});if(map.source!==undefined)table.classList.add('lead-all-table');var classes={time:'lead-col-time',name:'lead-col-name',mobile:'lead-col-mobile',source:'lead-col-source',desc:'lead-col-desc',operator:'lead-col-operator',group:'lead-col-group',status:'lead-col-status',result:'lead-col-result'};Object.keys(classes).forEach(function(key){var idx=map[key];if(idx!==undefined&&heads[idx])heads[idx].classList.add(classes[key])});table.querySelectorAll('tbody tr').forEach(function(tr){var cells=tr.children;Object.keys(classes).forEach(function(key){var idx=map[key];if(idx===undefined||!cells[idx])return;cells[idx].classList.add(classes[key]);if(key==='name'||key==='source'||key==='desc'||key==='group'){var full=(cells[idx].textContent||'').trim();cells[idx].title=full;cells[idx].setAttribute('aria-label',full)}})});});});</script>'''
        urgent = '''<script id="lead-urgent-actions-layout">document.addEventListener('DOMContentLoaded',function(){var urgentCard=Array.from(document.querySelectorAll('.lead-page .lead-card')).find(function(card){var h=card.querySelector('h3');return h&&(h.textContent||'').trim()==='نیازمند اقدام فوری'});if(!urgentCard)return;var table=urgentCard.querySelector('table.lead-table');if(!table)return;table.classList.add('lead-urgent-table');var headRow=table.querySelector('thead tr');if(headRow&&!headRow.querySelector('.lead-urgent-actions-head')){var th=document.createElement('th');th.className='lead-urgent-actions-head';th.textContent='عملیات';headRow.appendChild(th)}var heads=Array.from(table.querySelectorAll('thead th'));var statusIndex=heads.findIndex(function(th){return (th.textContent||'').trim()==='وضعیت'}),followupIndex=heads.findIndex(function(th){return (th.textContent||'').trim()==='پیگیری'});if(statusIndex>=0)heads[statusIndex].classList.add('lead-urgent-status');if(followupIndex>=0)heads[followupIndex].classList.add('lead-urgent-followup');table.querySelectorAll('tbody tr').forEach(function(tr){var first=tr.querySelector('td:first-child');if(!first||first.classList.contains('empty'))return;first.classList.add('lead-urgent-name');if(statusIndex>=0&&tr.children[statusIndex])tr.children[statusIndex].classList.add('lead-urgent-status');if(followupIndex>=0&&tr.children[followupIndex])tr.children[followupIndex].classList.add('lead-urgent-followup');var actionBox=Array.from(first.querySelectorAll('span')).find(function(span){return span.querySelector('a[href^="tel:"],a[href*="/referrals/leads/"]')});if(!actionBox)return;actionBox.classList.add('lead-urgent-actions');var td=document.createElement('td');td.className='lead-urgent-actions-cell';td.appendChild(actionBox);tr.appendChild(td)});var empty=table.querySelector('tbody tr td.empty');if(empty)empty.colSpan=7;});</script>'''
        extra += compact + urgent
        if admin:
            extra += '''<script id="lead-admin-controls">document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.lead-page a[href*="/referrals/leads/"][href$="/manage/"]').forEach(function(a){var m=a.getAttribute('href').match(/\\/referrals\\/leads\\/(\\d+)\\/manage\\//);if(!m)return;var host=a.parentElement;if(!host||host.querySelector('.lead-admin-actions'))return;var box=document.createElement('span');box.className='lead-admin-actions';box.innerHTML='<a class="lead-admin-edit" href="/lead-management/leads/'+m[1]+'/edit/">ویرایش</a><a class="lead-admin-delete" href="/lead-management/leads/'+m[1]+'/delete/">حذف</a>';host.appendChild(box);});});</script>'''
        html = html.replace('</body>', extra + '</body>')
        response.content = html.encode(response.charset or 'utf-8')
        response['Content-Length'] = str(len(response.content))
    except Exception:
        pass
    return response
