from django.urls import path
from . import views
from . import action_center_views
from . import camp_views
from . import referral_views
from .mcp import mcp_endpoint
urlpatterns=[path('service-worker.js',views.service_worker,name='service_worker'),path('camp/',camp_views.camp_dashboard,name='camp_dashboard'),
path('call-center/',referral_views.call_center_dashboard,name='call_center_dashboard'),
path('call-center/leads/<int:pk>/',referral_views.call_center_lead,name='call_center_lead'),
path('referrals/',referral_views.referral_dashboard,name='referral_dashboard'),
path('referrals/guide/',referral_views.referral_guide,name='referral_guide'),
path('referrals/network/',referral_views.referral_network,name='referral_network'),
path('referrals/network/new/',referral_views.referral_member_create,name='referral_member_create'),
path('referrals/leads/',referral_views.referral_lead_list,name='referral_lead_list'),
path('referrals/leads/new/',referral_views.referral_lead_create,name='referral_lead_create'),
path('referrals/leads/<int:pk>/manage/',referral_views.referral_lead_manage,name='referral_lead_manage'),
path('referrals/sales/',referral_views.referral_sales,name='referral_sales'),
path('referrals/sales/<int:lead_pk>/',referral_views.referral_sale_edit,name='referral_sale_edit'),
path('referrals/export/leads.csv',referral_views.referral_export_csv,name='referral_export_csv'),
path('referrals/export/crm.json',referral_views.referral_crm_export,name='referral_crm_export'),
path('r/<str:code>/',referral_views.public_referral_lead,name='public_referral_lead'),
path('r/<str:code>/qr/',referral_views.referral_qr,name='referral_qr'),
path('camp/purchases/',camp_views.purchase_list,name='camp_purchase_list'),
path('camp/purchases/new/',camp_views.purchase_create,name='camp_purchase_create'),
path('camp/purchases/<int:pk>/<str:action>/',camp_views.purchase_review,name='camp_purchase_review'),
path('camp/purchases/<int:pk>/invoice/',camp_views.invoice_create,name='camp_invoice_create'),
path('camp/inventory/',camp_views.inventory,name='camp_inventory'),
path('camp/inventory/new/',camp_views.inventory_item_create,name='camp_inventory_item_create'),
path('camp/inventory/<int:pk>/movement/',camp_views.inventory_movement,name='camp_inventory_movement'),
path('camp/workers/',camp_views.workers,name='camp_workers'),
path('camp/workers/new/',camp_views.worker_create,name='camp_worker_create'),
path('camp/workers/attendance/',camp_views.worker_attendance,name='camp_worker_attendance'),
path('camp/tasks/',camp_views.tasks,name='camp_tasks'),
path('camp/tasks/new/',camp_views.task_create,name='camp_task_create'),
path('camp/tasks/<int:pk>/<str:status>/',camp_views.task_toggle,name='camp_task_toggle'),
path('camp/projects/',camp_views.projects,name='camp_projects'),
path('camp/projects/new/',camp_views.project_create,name='camp_project_create'),
path('camp/food/',camp_views.food_plan,name='camp_food'),
path('camp/food/new/',camp_views.food_create,name='camp_food_create'),
path('camp/photos/',camp_views.photos,name='camp_photos'),
path('camp/photos/new/',camp_views.photo_create,name='camp_photo_create'),
path('camp/reports/',camp_views.reports,name='camp_reports'),
path('camp/commander/',camp_views.commander,name='camp_commander'),
path('camp/api/summary/',camp_views.camp_api_summary,name='camp_api_summary'),path('camp/demo/seed/',camp_views.seed_demo,name='camp_seed_demo'),path('ceo-score/',views.ceo_score_view,name='ceo_score'),path('trends/',views.trend_dashboard,name='trend_dashboard'),path('calendar/',views.management_calendar,name='management_calendar'),path('calendar/new/',views.management_event_add,name='management_event_add'),path('audit/',views.audit_log_view,name='audit_log'),path('api/ceo-score/',views.ceo_score_api,name='ceo_score_api'),path('brief/',views.morning_brief,name='morning_brief'),path('command/',views.command_center,name='command_center'),path('action-center/quick/',action_center_views.quick_action,name='action_center_quick_action'),path('action-center/',views.action_center,name='action_center'),path('employees/<int:pk>/360/',views.employee_360,name='employee_360'),path('employees/<int:pk>/action/',views.personnel_action_add,name='personnel_action_add'),path('actions/<int:pk>/ack/',views.personnel_action_ack,name='personnel_action_ack'),path('goals/',views.goals,name='goals'),path('goals/new/',views.goal_add,name='goal_add'),path('service-requests/',views.internal_requests,name='internal_requests'),path('service-requests/new/',views.internal_request_add,name='internal_request_add'),
path('mcp/',mcp_endpoint,name='mcp_endpoint'),path('api/health/',views.health_check,name='health_check'),path('api/attendance/today/',views.attendance_api_today,name='attendance_api_today'),
path('api/management/attendance/summary/',views.management_attendance_summary_api,name='management_attendance_summary_api'),path('api/management/query/',views.management_query_api,name='management_query_api'),path('api/management/finance/summary/',views.management_finance_summary_api,name='management_finance_summary_api'),

path('api/management/employee/status/',views.management_employee_status_api,name='management_employee_status_api'),
path('today/',views.executive_today,name='executive_today'),path('live/',views.branch_live_dashboard,name='branch_live_dashboard'),path('api/live/',views.branch_live_api,name='branch_live_api'),path('api/alerts/run/',views.smart_alerts_run,name='smart_alerts_run'),
path('notifications/',views.notifications_list,name='notifications'),
path('shifts/',views.shift_list,name='shift_list'),path('shifts/new/',views.shift_create,name='shift_create'),path('shifts/assign/',views.shift_assign,name='shift_assign'),
path('attendance/corrections/',views.correction_list,name='correction_list'),path('attendance/corrections/new/',views.correction_create,name='correction_create'),path('attendance/corrections/<int:pk>/review/',views.correction_review,name='correction_review'),
path('kpi/automatic/',views.automatic_kpi_dashboard,name='automatic_kpi_dashboard'),
path('login/',views.login_view,name='login'),path('logout/',views.logout_view,name='logout'),path('',views.dashboard,name='dashboard'),
path('reports/',views.report_list,name='report_list'),path('reports/new/',views.report_create,name='report_create'),path('reports/<int:pk>/',views.report_detail,name='report_detail'),
path('tasks/',views.task_list,name='task_list'),path('tasks/new/',views.task_create,name='task_create'),path('tasks/<int:pk>/',views.task_update,name='task_update'),
path('announcements/',views.announcement_list,name='announcement_list'),path('announcements/new/',views.announcement_create,name='announcement_create'),
path('blackboard/',views.blackboard_manage,name='blackboard_manage'),path('blackboard/new/',views.blackboard_edit,name='blackboard_create'),path('blackboard/<int:pk>/edit/',views.blackboard_edit,name='blackboard_edit'),
path('requests/',views.leave_list,name='leave_list'),path('requests/new/',views.leave_create,name='leave_create'),path('requests/<int:pk>/review/',views.leave_review,name='leave_review'),
path('attendance/',views.attendance,name='attendance'),path('finance/',views.finance_dashboard,name='finance_dashboard'),path('finance/entry/',views.finance_entry,name='finance_entry'),path('finance/entries/<int:pk>/<str:action>/',views.finance_entry_review,name='finance_entry_review'),path('finance/sync/',views.finance_sync,name='finance_sync'),path('analytics/',views.analytics_dashboard,name='analytics_dashboard'),path('kpi/',views.kpi_list,name='kpi_list'),path('kpi/new/',views.kpi_create,name='kpi_create'),path('scores/new/',views.score_create,name='score_create'),path('attendance/team/',views.attendance_team,name='attendance_team'),path('attendance/new/',views.attendance_create,name='attendance_create'),path('attendance/<int:pk>/edit/',views.attendance_edit,name='attendance_edit'),
path('sop/',views.sop_list,name='sop_list'),path('employees/',views.employee_list,name='employee_list'),path('employees/<int:pk>/file/',views.employee_file,name='employee_file'),path('employees/<int:pk>/edit/',views.employee_edit,name='employee_edit'),path('employees/<int:pk>/reports/',views.employee_reports,name='employee_reports'),path('employees/<int:pk>/attendance/',views.employee_attendance,name='employee_attendance'),path('employees/<int:pk>/tasks/new/',views.employee_task_create,name='employee_task_create'),path('employees/<int:pk>/documents/new/',views.employee_document_add,name='employee_document_add'),path('employees/new/',views.employee_create,name='employee_create'),path('employees/<int:pk>/photo/',views.employee_avatar_edit,name='employee_avatar_edit'),path('checklists/',views.checklist_today,name='checklist_today'),path('checklists/toggle/<int:item_id>/',views.checklist_toggle,name='checklist_toggle'),path('checklists/manage/',views.checklist_templates,name='checklist_templates'),path('checklists/manage/new/',views.checklist_template_create,name='checklist_template_create'),path('checklists/manage/<int:pk>/',views.checklist_template_detail,name='checklist_template_detail'),path('checklists/team/',views.checklist_team_status,name='checklist_team_status'),path('profile/',views.profile_view,name='profile'),
path('device-issues/new/',views.device_issue_create,name='device_issue_create'),
path('device-issues/mine/',views.device_issue_mine,name='device_issue_mine'),
path('device-issues/manage/',views.device_issue_manage,name='device_issue_manage'),
path('device-issues/<int:pk>/review/',views.device_issue_review,name='device_issue_review'),
path('guidelines/',views.my_guidelines,name='my_guidelines'),
path('guidelines/<int:pk>/ack/',views.guideline_ack,name='guideline_ack'),
path('guidelines/manage/',views.guidelines_manage,name='guidelines_manage'),
path('guidelines/manage/new/',views.guideline_create,name='guideline_create'),
path('job-duties/new/',views.job_duty_create,name='job_duty_create')]
